# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='suggest',
            options={'ordering': ['-created_at'], 'verbose_name': '意见', 'verbose_name_plural': '意见'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
