# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 16:38
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180610_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述/摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.image_upload_to, verbose_name='文章图片'),
        ),
    ]
