# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180610_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.FileField(upload_to='', verbose_name='文章'),
        ),
    ]
