# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:34
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180610_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.FileField(upload_to=blog.models.article_upload_to, verbose_name='文章'),
        ),
    ]
