# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='user/avatars', verbose_name='头像')),
                ('sex', models.CharField(choices=[('1', '男性'), ('2', '女性'), ('0', '未知')], default=0, max_length=1, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户补充',
                'verbose_name_plural': '用户补充',
            },
        ),
    ]
